Add transform properties to VideoSource node
lumeohq/lumeo-types-rs pull request #59
Opened 2021-06-09 14:42 UTC by DmitrySamoylov

Story details: https://app.clubhouse.io/lumeo/story/3544

2021-06-09 15:02 UTC, jplatte approved these changes

2021-06-09 15:41 UTC, SIGLOST approved these changes
lgtm, minor comment

2021-06-09 15:41 UTC, SIGLOST commented on pipeline/src/node_properties/video_source_properties.rs
> +    /// Changes resolution, for example 640x480 becomes 480x600.
on the comment I guess you mean 480x640  :smiley:  (also on L61)

2021-06-09 16:27 UTC, zeenix commented on pipeline/src/node_properties/video_source_properties.rs
> +    Cw90,
I'd very much prefer not using unknown abbreviations: `CounterClock90` etc.

2021-06-09 16:28 UTC, zeenix requested changes
LGTM otherwise.

2021-06-10 10:28 UTC, zeenix approved these changes

2021-06-10 11:06 UTC, merged